---
postgres_version: "15"
postgres_authentications_local: "mquser"
postgres_authentications_host:
  - { user: "mquser", address: "127.0.0.1/32", notes: "localhost" }
postgres_roles:
  - { user: "mquser", roles: "SUPERUSER", password: "changeme" }
postgres_autoconf_src_path: ""
...
