---
- name: "Install required packages"
  apt:
    update_cache: true
    name:
      - "gpg"

- name: "Install apt key"
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

- name: "Add apt repository"
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
    filename: 'pgdg'

- name: "Install PostgreSQL"
  apt:
    update_cache: true
    name:
      - "postgresql-{{postgres_version}}"

- name: "Restart PostgresSQL"
  service:
    name: "postgresql"
    state: "restarted"
...