---
- name: "Setup PostgreSQL"
  hosts: all
  gather_facts: true
  become: true

  roles:
    - { role: 'postgres',
        postgres_version: '10',
        postgres_lc_ctype: "C.UTF-8",
        postgres_lc_collate: "C.UTF-8"
    }
...
