---
- name: "Setup VM"
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: "Update VM"
      apt:
        update_cache: true
        upgrade: true
        autoremove: true
        purge: true
...